version: '3.8'

services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    # 以下はdephneを使う場合
    # command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    ports:
      - 8000:8000
    volumes:
      - ./src:/code